In [ ]:
!pip install tensorflow keras numpy mnist matplotlib

In [25]:
import numpy as np
import pandas as pd
import mnist
import matplotlib.pyplot as plt

from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical

In [26]:
train_images = mnist.train_images()
train_labels = mnist.train_labels()
test_images = mnist.test_images()
test_labels = mnist.test_labels()

In [27]:
np.set_printoptions(linewidth = 200)
pd.options.display.max_rows = 10
pd.options.display.float_format = "{:.1f}".format
print(train_images[0])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3  18  18  18 126 136 175  26 166 255 247 127   0   0   0   0]
 [  0   0   0   0   0   0   0   0  30  36  94 154 170 253 253 253 253 253 225 172 253 242 195  64   0   0   0   0]
 [  0   0   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251  93  82  82  56  39   0   0   0   0   0]
 [  0   0   0   0   0   0   0  18 219 253 253 253 253 253 198 182 247 241   0   

In [28]:
train_images = (train_images/255) -0.5
test_images = (test_images/255) - 0.5
train_images = train_images.reshape((-1,784))
test_images = test_images.reshape((-1,784))
print(train_images.shape)
print(test_images.shape)

(60000, 784)
(10000, 784)


In [29]:
model = Sequential()
model.add(Dense(64 , activation='relu' , input_dim = 784))
model.add(Dense(64 , activation='relu'))
model.add(Dense(10 , activation='softmax'))

In [30]:
model.compile(
   optimizer = 'adam' ,
   loss = 'categorical_crossentropy',
   metrics = ['accuracy']
)

In [31]:
model.fit(
    train_images,
    to_categorical(train_labels),
    epochs = 5,
    batch_size = 32
)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.3771 - accuracy: 0.8868
Epoch 2/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1898 - accuracy: 0.9420
Epoch 3/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1473 - accuracy: 0.9545
Epoch 4/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1216 - accuracy: 0.9629
Epoch 5/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1049 - accuracy: 0.9670


In [32]:
model.evaluate(test_images,to_categorical(test_labels))

313/313 [==============================] - 0s 920us/step - loss: 0.1172 - accuracy: 0.9621


[0.11720851063728333, 0.9621000289916992]

In [33]:
model.save_weights('model.h5')

In [35]:
predictions = model.predict(test_images[:5])
predictions = np.argmax(predictions , axis = 1)

In [36]:
print(predictions)

[7 2 1 0 4]
