In [1]:
import tensorflow.keras
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPooling2D,Input
from tensorflow.keras import regularizers
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras import backend as K

(x_train, y_train) , (x_test,y_test) = mnist.load_data()
print("shape of x_train",x_train.shape)
print("shape of y_train",y_train.shape)
print("shape of x_test",x_test.shape)
print("shape of y_test",y_test.shape)

shape of x_train (60000, 28, 28)
shape of y_train (60000,)
shape of x_test (10000, 28, 28)
shape of y_test (10000,)


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

np.set_printoptions(linewidth = 200)
pd.options.display.max_rows = 10
pd.options.display.float_format = "{:.1f}".format

print(x_train[0])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3  18  18  18 126 136 175  26 166 255 247 127   0   0   0   0]
 [  0   0   0   0   0   0   0   0  30  36  94 154 170 253 253 253 253 253 225 172 253 242 195  64   0   0   0   0]
 [  0   0   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251  93  82  82  56  39   0   0   0   0   0]
 [  0   0   0   0   0   0   0  18 219 253 253 253 253 253 198 182 247 241   0   

In [3]:
#reshaping
img_rows, img_cols = 28, 28
if K.image_data_format() == 'channels_first':
    x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
    x_test = x_test.reshape(x_test.shape[0], 1, img_rows, img_cols)
    input_shape = (1, img_rows, img_cols)
else:
    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
    x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
    input_shape = (img_rows, img_cols, 1)

# x_train , x_test = np.expand_dims(x_train, axis =-1) , np.expand_dims(x_test,axis =-1)

In [4]:
print("shape of x_train",x_train.shape)
print("shape of y_train",y_train.shape)
print("shape of x_test",x_test.shape)
print("shape of y_test",y_test.shape)

shape of x_train (60000, 28, 28, 1)
shape of y_train (60000,)
shape of x_test (10000, 28, 28, 1)
shape of y_test (10000,)


In [5]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train = x_train / 255
x_test  = x_test  / 255

print("shape of x_train",x_train.shape)
print("shape of y_train",y_train.shape)
print("shape of x_test",x_test.shape)
print("shape of y_test",y_test.shape)

shape of x_train (60000, 28, 28, 1)
shape of y_train (60000,)
shape of x_test (10000, 28, 28, 1)
shape of y_test (10000,)


In [6]:
batch_size = 128
num_classes = 10
epochs = 12

y_train = to_categorical(y_train,num_classes)
y_test = to_categorical(y_test,num_classes)

In [7]:
#without max_pooling

model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape))  #conv_layer
model.add(Flatten()) #flatten layer
model.add(Dense(num_classes, activation='softmax')) #output
model.compile(loss='categorical_crossentropy', optimizer='adam',
              metrics=['accuracy'])

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 26, 26, 32)        320       
_________________________________________________________________
flatten (Flatten)            (None, 21632)             0         
_________________________________________________________________
dense (Dense)                (None, 10)                216330    
Total params: 216,650
Trainable params: 216,650
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.fit(x_train , y_train , batch_size=batch_size, epochs=epochs, verbose = 2, validation_data=(x_test,y_test))
score = model.evaluate(x_test,y_test,verbose = 0)


Epoch 1/12
469/469 - 1s - loss: 0.2633 - accuracy: 0.9253 - val_loss: 0.1215 - val_accuracy: 0.9660
Epoch 2/12
469/469 - 1s - loss: 0.0945 - accuracy: 0.9735 - val_loss: 0.0784 - val_accuracy: 0.9754
Epoch 3/12
469/469 - 1s - loss: 0.0669 - accuracy: 0.9804 - val_loss: 0.0721 - val_accuracy: 0.9772
Epoch 4/12
469/469 - 1s - loss: 0.0525 - accuracy: 0.9849 - val_loss: 0.0649 - val_accuracy: 0.9792
Epoch 5/12
469/469 - 1s - loss: 0.0437 - accuracy: 0.9871 - val_loss: 0.0627 - val_accuracy: 0.9808
Epoch 6/12
469/469 - 1s - loss: 0.0358 - accuracy: 0.9891 - val_loss: 0.0577 - val_accuracy: 0.9823
Epoch 7/12
469/469 - 1s - loss: 0.0316 - accuracy: 0.9900 - val_loss: 0.0608 - val_accuracy: 0.9812
Epoch 8/12
469/469 - 1s - loss: 0.0262 - accuracy: 0.9921 - val_loss: 0.0648 - val_accuracy: 0.9813
Epoch 9/12
469/469 - 1s - loss: 0.0231 - accuracy: 0.9932 - val_loss: 0.0643 - val_accuracy: 0.9814
Epoch 10/12
469/469 - 1s - loss: 0.0196 - accuracy: 0.9946 - val_loss: 0.0635 - val_accuracy: 0.9823

In [10]:
#adding max_pooling

model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape))
model.add(MaxPooling2D(pool_size=(2, 2))) # max_pooling
model.add(Flatten())
model.add(Dense(num_classes, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam',
              metrics=['accuracy'])

In [11]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 13, 13, 32)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 5408)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                54090     
Total params: 54,410
Trainable params: 54,410
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.fit(x_train , y_train , batch_size=batch_size, epochs=epochs, verbose = 2, validation_data=(x_test,y_test))
score = model.evaluate(x_test,y_test,verbose = 0)

Epoch 1/12
469/469 - 1s - loss: 0.3389 - accuracy: 0.9092 - val_loss: 0.1406 - val_accuracy: 0.9601
Epoch 2/12
469/469 - 1s - loss: 0.1138 - accuracy: 0.9684 - val_loss: 0.0857 - val_accuracy: 0.9745
Epoch 3/12
469/469 - 1s - loss: 0.0805 - accuracy: 0.9778 - val_loss: 0.0695 - val_accuracy: 0.9773
Epoch 4/12
469/469 - 1s - loss: 0.0656 - accuracy: 0.9815 - val_loss: 0.0653 - val_accuracy: 0.9800
Epoch 5/12
469/469 - 1s - loss: 0.0566 - accuracy: 0.9839 - val_loss: 0.0570 - val_accuracy: 0.9813
Epoch 6/12
469/469 - 1s - loss: 0.0505 - accuracy: 0.9859 - val_loss: 0.0618 - val_accuracy: 0.9804
Epoch 7/12
469/469 - 1s - loss: 0.0462 - accuracy: 0.9863 - val_loss: 0.0533 - val_accuracy: 0.9820
Epoch 8/12
469/469 - 1s - loss: 0.0419 - accuracy: 0.9877 - val_loss: 0.0537 - val_accuracy: 0.9823
Epoch 9/12
469/469 - 1s - loss: 0.0378 - accuracy: 0.9891 - val_loss: 0.0523 - val_accuracy: 0.9827
Epoch 10/12
469/469 - 1s - loss: 0.0351 - accuracy: 0.9896 - val_loss: 0.0535 - val_accuracy: 0.9834

In [13]:
#adding dropout layer
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape))

model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(num_classes, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam',
              metrics=['accuracy'])

In [14]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_2 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 13, 13, 32)        0         
_________________________________________________________________
dropout (Dropout)            (None, 13, 13, 32)        0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 5408)              0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                54090     
Total params: 54,410
Trainable params: 54,410
Non-trainable params: 0
_________________________________________________________________


In [15]:
model.fit(x_train , y_train , batch_size=batch_size, epochs=epochs, verbose = 2, validation_data=(x_test,y_test))
score = model.evaluate(x_test,y_test,verbose = 0)

Epoch 1/12
469/469 - 1s - loss: 0.3588 - accuracy: 0.9053 - val_loss: 0.1518 - val_accuracy: 0.9594
Epoch 2/12
469/469 - 1s - loss: 0.1355 - accuracy: 0.9616 - val_loss: 0.0977 - val_accuracy: 0.9722
Epoch 3/12
469/469 - 1s - loss: 0.0983 - accuracy: 0.9721 - val_loss: 0.0789 - val_accuracy: 0.9763
Epoch 4/12
469/469 - 1s - loss: 0.0831 - accuracy: 0.9763 - val_loss: 0.0676 - val_accuracy: 0.9784
Epoch 5/12
469/469 - 1s - loss: 0.0742 - accuracy: 0.9784 - val_loss: 0.0608 - val_accuracy: 0.9792
Epoch 6/12
469/469 - 1s - loss: 0.0680 - accuracy: 0.9802 - val_loss: 0.0607 - val_accuracy: 0.9801
Epoch 7/12
469/469 - 1s - loss: 0.0628 - accuracy: 0.9806 - val_loss: 0.0547 - val_accuracy: 0.9813
Epoch 8/12
469/469 - 1s - loss: 0.0584 - accuracy: 0.9822 - val_loss: 0.0534 - val_accuracy: 0.9823
Epoch 9/12
469/469 - 1s - loss: 0.0552 - accuracy: 0.9829 - val_loss: 0.0538 - val_accuracy: 0.9820
Epoch 10/12
469/469 - 1s - loss: 0.0526 - accuracy: 0.9837 - val_loss: 0.0521 - val_accuracy: 0.9829

In [16]:
#adding 1 more conv , dropout and dense layers
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam',
              metrics=['accuracy'])

In [17]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 24, 24, 64)        18496     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 12, 12, 64)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 12, 12, 64)        0         
_________________________________________________________________
flatten_3 (Flatten)          (None, 9216)              0         
_________________________________________________________________
dense_3 (Dense)              (None, 128)               1179776   
_________________________________________________________________
dropout_2 (Dropout)          (None, 128)              

In [18]:
model.fit(x_train , y_train , batch_size=batch_size, epochs=epochs, verbose = 2, validation_data=(x_test,y_test))
score = model.evaluate(x_test,y_test,verbose = 0)

Epoch 1/12
469/469 - 3s - loss: 0.2491 - accuracy: 0.9242 - val_loss: 0.0592 - val_accuracy: 0.9803
Epoch 2/12
469/469 - 2s - loss: 0.0881 - accuracy: 0.9739 - val_loss: 0.0376 - val_accuracy: 0.9873
Epoch 3/12
469/469 - 2s - loss: 0.0674 - accuracy: 0.9795 - val_loss: 0.0360 - val_accuracy: 0.9884
Epoch 4/12
469/469 - 2s - loss: 0.0535 - accuracy: 0.9836 - val_loss: 0.0306 - val_accuracy: 0.9901
Epoch 5/12
469/469 - 3s - loss: 0.0450 - accuracy: 0.9860 - val_loss: 0.0296 - val_accuracy: 0.9910
Epoch 6/12
469/469 - 2s - loss: 0.0404 - accuracy: 0.9872 - val_loss: 0.0253 - val_accuracy: 0.9911
Epoch 7/12
469/469 - 2s - loss: 0.0357 - accuracy: 0.9890 - val_loss: 0.0273 - val_accuracy: 0.9918
Epoch 8/12
469/469 - 2s - loss: 0.0304 - accuracy: 0.9904 - val_loss: 0.0272 - val_accuracy: 0.9918
Epoch 9/12
469/469 - 2s - loss: 0.0297 - accuracy: 0.9902 - val_loss: 0.0281 - val_accuracy: 0.9917
Epoch 10/12
469/469 - 2s - loss: 0.0269 - accuracy: 0.9913 - val_loss: 0.0298 - val_accuracy: 0.9919

In [19]:
model.evaluate(x_test,y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.0294 - accuracy: 0.9918


[0.02940916083753109, 0.9918000102043152]